import type { Metadata } from 'next';
import localFont from 'next/font/local';
import './globals.css';
import TopNavigation from '@/components/topNavigation';
import BottomInfo from '@/components/bottomInfo';
import '@rainbow-me/rainbowkit/styles.css';
import { Providers } from '@/components/Providers';

const geistSans = localFont({
  src: './fonts/GeistVF.woff',
  variable: '--font-geist-sans',
  weight: '100 900',
});
const geistMono = localFont({
  src: './fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
  weight: '100 900',
});
const neueMon = localFont({
  src: './fonts/NeueMontreal-Light.otf',
  variable: '--font-neue-mon',
});
const dx = localFont({
  src: './fonts/Dx Dynamix-Free-Personal-Use.woff',
  variable: '--font-dx-mon',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${neueMon.variable} ${dx.variable} antialiased`}>
        <Providers>
          <TopNavigation />
          {children}
          <footer>
            <BottomInfo />
          </footer>
        </Providers>
      </body>
    </html>
  );
}
